Author: Swopnil N. Shrestha <br>
Organization: Luther College <br>
Email: swopnil@pm.me <br>
Version: 0.0.1

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/data/bikeshare/data/boston/boston.csv")
stations = pd.read_csv("/data/bikeshare/data/boston/stations.csv")

In [4]:
# View dataFrame
df

,seq_id,hubway_id,status,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,zip_code,birth_date,gender
0,1,8,Closed,9,7/28/2011 10:12:00,23.0,7/28/2011 10:12:00,23.0,B00468,Registered,'97217,1976.0,Male
1,2,9,Closed,220,7/28/2011 10:21:00,23.0,7/28/2011 10:25:00,23.0,B00554,Registered,'02215,1966.0,Male
2,3,10,Closed,56,7/28/2011 10:33:00,23.0,7/28/2011 10:34:00,23.0,B00456,Registered,'02108,1943.0,Male
3,4,11,Closed,64,7/28/2011 10:35:00,23.0,7/28/2011 10:36:00,23.0,B00554,Registered,'02116,1981.0,Female
4,5,12,Closed,12,7/28/2011 10:37:00,23.0,7/28/2011 10:37:00,23.0,B00554,Registered,'97214,1983.0,Female
5,6,13,Closed,19,7/28/2011 10:39:00,23.0,7/28/2011 10:39:00,23.0,B00456,Registered,'02021,1951.0,Male
6,7,14,Closed,24,7/28/2011 10:47:00,23.0,7/28/2011 10:47:00,23.0,B00554,Registered,'02140,1971.0,Female
7,8,15,Closed,7,7/28/2011 10:48:00,23.0,7/28/2011 10:48:00,23.0,B00554,Registered,'02140,1971.0,Female
8,9,16,Closed,8,7/28/2011 11:01:00,23.0,7/28/2011 11:01:00,23.0,B00554,Registered,'97214,1983.0,Female
9,10,17,Closed,1108,7/28/2011 11:55:00,47.0,7/28/2011 12:13:00,40.0,B00550,Registered,'01867,1994.0,Male
10,11,18,Closed,1055,7/28/2011 11:55:00,47.0,7/28/2011 12:13:00,40.0,B00580,Registered,'01867,1956.0,Male
11,12,19,Closed,1042,7/28/2011 11:55:00,47.0,7/28/2011 12:12:00,40.0,B00539,Registered,'01867,1959.0,Female
12,13,23,Closed,994,7/28/2011 12:00:00,40.0,7/28/2011 12:16:00,47.0,B00368,Casual,NaN,NaN,NaN
13,14,25,Closed,15,7/28/2011 12:00:00,22.0,7/28/2011 12:00:00,22.0,B00442,Registered,'02446,1982.0,Male
14,15,27,Closed,952,7/28/2011 12:00:00,40.0,7/28/2011 12:16:00,23.0,B00556,Registered,'02128,1944.0,Male
15,16,28,Closed,32,7/28/2011 12:00:00,22.0,7/28/2011 12:01:00,22.0,B00316,Registered,'02115,1960.0,Female
16,17,29,Closed,1261,7/28/2011 12:00:00,22.0,7/28/2011 12:21:00,45.0,B00454,Registered,'02492,1975.0,Male
17,18,30,Closed,7,7/28/2011 12:00:00,22.0,7/28/2011 12:00:00,22.0,B00404,Registered,'02446,1956.0,Male
18,19,31,Closed,1020,7/28/2011 12:01:00,38.0,7/28/2011 12:18:00,36.0,B00147,Registered,'02118,1987.0,Female
19,20,33,Closed,1264,7/28/2011 12:01:00,38.0,7/28/2011 12:22:00,44.0,B00165,Registered,'02139,1985.0,Female
20,21,34,Closed,1043,7/28/2011 12:01:00,38.0,7/28/2011 12:18:00,44.0,B00527,Registered,'02351,1978.0,Male
21,22,35,Closed,969,7/28/2011 12:01:00,22.0,7/28/2011 12:17:00,44.0,B00487,Registered,'02143,1971.0,Male
22,23,37,Closed,1582,7/28/2011 12:01:00,38.0,7/28/2011 12:27:00,10.0,B00093,Registered,'02130,1980.0,Female
23,24,38,Closed,620,7/28/2011 12:01:00,22.0,7/28/2011 12:12:00,20.0,B00375,Registered,'02474,1955.0,Female
24,25,40,Closed,7,7/28/2011 12:02:00,22.0,7/28/2011 12:02:00,22.0,B00275,Registered,'02140,1971.0,Female
25,26,41,Closed,771,7/28/2011 12:02:00,38.0,7/28/2011 12:15:00,42.0,B00279,Registered,'02108,1943.0,Male
26,27,42,Closed,1222,7/28/2011 12:02:00,38.0,7/28/2011 12:22:00,44.0,B00074,Registered,'02143,1972.0,Female
27,28,43,Closed,4,7/28/2011 12:02:00,22.0,7/28/2011 12:02:00,22.0,B00137,Registered,'01776,1949.0,Male
28,29,44,Closed,5,7/28/2011 12:02:00,22.0,7/28/2011 12:02:00,22.0,B00082,Registered,'01880,1968.0,Male
29,30,45,Closed,824,7/28/2011 12:02:00,22.0,7/28/2011 12:16:00,38.0,B00460,Registered,'02131,1967.0,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1578995,1578996,1747993,Closed,540,11/30/2013 20:17:00,76.0,11/30/2013 20:26:00,91.0,T01268,Registered,'02139,NaN,Male
1578996,1578997,1747994,Closed,300,11/30/2013 20:23:00,136.0,11/30/2013 20:28:00,67.0,T01352,Registered,'02142,NaN,Male
1578997,1578998,1747995,Closed,420,11/30/2013 20:23:00,76.0,11/30/2013 20:30:00,80.0,T01185,Registered,'02215,NaN,Male
1578998,1578999,1747996,Closed,13980,11/30/2013 20:23:00,74.0,12/1/2013 00:16:00,137.0,T01334,Registered,'02138,NaN,Male
1578999,1579000,1747997,Closed,300,11/30/2013 20:33:00,133.0,11/30/2013 20:38:00,74.0,T01217,Casual,NaN,NaN,NaN
1579000,1579001,1747998,Closed,1200,11/30/2013 20:46:00,137.0,11/30/2013 21:06:00,80.0,T01146,Registered,'02171,NaN,Male
1579001,1579002,1747999,Closed,360,11/30/2013 20:50:00,136.0,11/30/2013 20:56:00,67.0,T01328,Registered,'02142,NaN,Male
1579002,1579003,1748000,Closed,300,11/30/2013 20:59:00,68.0,11/30/2013 21:04:00,95.0,T01182,Registered,'02445,NaN,Male
1579003,1579004,1748001,Closed,300,11/30/2013 21:01:00,84.0,11/30/2013 21:06:00,128.0,B01468,Registered,'02142,NaN,Male
1579004,1579005,1748002,Closed,960,11/30/2013 21:07:00,68.0,11/30/2013 21:23:00,74.0,T01439,Registered,'02215,NaN,Male
1579005,1579006,1748003,Closed,180,11/30/2013 21:10:00,72.0,11/30/2013 21:13:00,91.0,T01351,Registered,'02142,NaN,Female
1579006,1579007,1748004,Closed,420,11/30/2013 21:19:00,96.0,11/30/2013 21:26:00,76.0,T01175,Registered,'02139,NaN,Female
1579007,1579008,1748005,Closed,300,11/30/2013 21:41:00,67.0,11/30/2013 21:46:00,68.0,T01343,Registered,'02139,NaN,Male
1579008,1579009,1748006,Closed,300,11/30/2013 21:47:00,137.0,11/30/2013 21:52:00,133.0,B01489,Registered,'02452,NaN,Male
1579009,1579010,1748007,Closed,780,11/30/2013 21:54:00,129.0,11/30/2013 22:07:00,91.0,T01350,Registered,'02139,NaN,Male
1579010,1579011,1748008,Closed,540,11/30/2013 21:55:00,76.0,11/30/2013 22:04:00,68.0,T01175,Registered,'02139,NaN,Male
1579011,1579012,1748009,Closed,1440,11/30/2013 22:15:00,130.0,11/30/2013 22:39:00,68.0,B01480,Registered,'02139,NaN,Male
1579012,1579013,1748010,Closed,480,11/30/2013 22:25:00,137.0,11/30/2013 22:33:00,74.0,T01308,Registered,'02140,NaN,Male
1579013,1579014,1748011,Closed,420,11/30/2013 22:25:00,137.0,11/30/2013 22:32:00,74.0,T01043,Registered,'02139,NaN,Female
1579014,1579015,1748012,Closed,360,11/30/2013 22:51:00,67.0,11/30/2013 22:57:00,68.0,T01352,Registered,'02139,NaN,Male
1579015,1579016,1748013,Closed,300,11/30/2013 22:53:00,74.0,11/30/2013 22:58:00,87.0,T01217,Registered,'02138,NaN,Female
1579016,1579017,1748014,Closed,120,11/30/2013 23:07:00,128.0,11/30/2013 23:09:00,136.0,B01468,Registered,'02142,NaN,Male
1579017,1579018,1748015,Closed,900,11/30/2013 23:17:00,76.0,11/30/2013 23:32:00,96.0,B00585,Registered,'02131,NaN,Female
1579018,1579019,1748016,Closed,240,11/30/2013 23:24:00,134.0,11/30/2013 23:28:00,139.0,T01195,Registered,'02478,NaN,Male
1579019,1579020,1748017,Closed,360,11/30/2013 23:24:00,129.0,11/30/2013 23:30:00,133.0,T01069,Registered,'02138,NaN,Male
1579020,1579021,1748018,Closed,720,11/30/2013 23:30:00,130.0,11/30/2013 23:42:00,90.0,T01341,Registered,'02141,NaN,Male
1579021,1579022,1748019,Closed,480,11/30/2013 23:32:00,67.0,11/30/2013 23:40:00,88.0,T01328,Registered,'02143,NaN,Male
1579022,1579023,1748020,Closed,540,11/30/2013 23:32:00,137.0,11/30/2013 23:41:00,133.0,T01310,Casual,NaN,NaN,NaN
1579023,1579024,1748021,Closed,120,11/30/2013 23:36:00,76.0,11/30/2013 23:38:00,68.0,B01478,Registered,'02141,NaN,Male
1579024,1579025,1748022,Closed,420,11/30/2013 23:39:00,68.0,11/30/2013 23:46:00,95.0,T01352,Registered,'02143,NaN,Female

In [6]:
# View Stations
stations

,id,terminal,station,municipal,lat,lng,status
0,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing
1,4,C32000,Tremont St. at Berkeley St.,Boston,42.345392,-71.069616,Existing
2,5,B32012,Northeastern U / North Parking Lot,Boston,42.341814,-71.090179,Existing
3,6,D32000,Cambridge St. at Joy St.,Boston,42.361285,-71.065140,Existing
4,7,A32000,Fan Pier,Boston,42.353412,-71.044624,Existing
5,8,A32001,Union Square - Brighton Ave. at Cambridge St.,Boston,42.353334,-71.137313,Existing
6,9,A32002,Agganis Arena - 925 Comm Ave.,Boston,42.351313,-71.116174,Existing
7,10,A32003,B.U. Central - 725 Comm. Ave.,Boston,42.350075,-71.105884,Existing
8,11,A32004,Longwood Ave / Binney St,Boston,42.338629,-71.106500,Existing
9,12,B32002,Ruggles Station / Columbus Ave.,Boston,42.335911,-71.088496,Existing
10,13,C32002,Boston Medical Center - 721 Mass. Ave.,Boston,42.334057,-71.074030,Removed
11,14,B32003,HMS / HSPH - Ave. Louis Pasteur at Longwood Ave.,Boston,42.337171,-71.102797,Existing
12,15,A32005,Harvard Real Estate - Brighton Mills - 370 Wes...,Boston,42.361667,-71.138020,Existing
13,16,C32003,Back Bay / South End Station,Boston,42.347433,-71.076163,Existing
14,17,A32006,Harvard University Housing - 111 Western Ave. ...,Boston,42.365074,-71.119581,Existing
15,18,A32007,Harvard Real Estate - 219 Western Ave. at Nort...,Boston,42.363370,-71.129791,Existing
16,19,A32008,Buswell Park,Boston,42.347527,-71.105828,Existing
17,20,B32004,Aquarium Station - 200 Atlantic Ave.,Boston,42.359770,-71.051601,Existing
18,21,C32007,Prudential Center / Belvidere,Boston,42.345959,-71.082578,Existing
19,22,A32010,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547,Existing
20,23,B32008,Mayor Thomas M. Menino - Government Center,Boston,42.359677,-71.059364,Removed
21,24,B32007,Seaport Square - Seaport Blvd. at Boston Wharf,Boston,42.351821,-71.045461,Existing
22,25,A32009,Tremont St / W Newton St,Boston,42.341332,-71.076847,Existing
23,26,D32002,Washington St. at Waltham St.,Boston,42.341522,-71.068922,Existing
24,27,C32001,Roxbury Crossing Station,Boston,42.331567,-71.094734,Existing
25,29,A32011,Innovation Lab - 125 Western Ave. at Batten Way,Boston,42.363732,-71.124565,Existing
26,30,B32013,Brigham Cir / Huntington Ave,Boston,42.334073,-71.105221,Existing
27,31,B32014,Seaport Hotel,Boston,42.348833,-71.041747,Existing
28,32,B32015,Landmark Centre,Boston,42.343912,-71.102221,Existing
29,33,B32010,Kenmore Sq / Comm Ave,Boston,42.349046,-71.096831,Existing
...,...,...,...,...,...,...,...
112,116,D32024,Charles St at Beacon St,Boston,42.356052,-71.069849,Existing
113,117,D32025,Milk St at India St,Boston,42.358508,-71.052984,Existing
114,118,D32026,Hayes Square at Vine St.,Boston,42.377022,-71.056605,Existing
115,119,D32027,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.076550,Existing
116,120,E32001,JP Monument - South St at Centre St,Boston,42.309467,-71.115645,Existing
117,121,E32002,JP Centre - Centre Street at Myrtle Street,Boston,42.313090,-71.114175,Existing
118,122,E32003,Hyde Square at Barbara St,Boston,42.320998,-71.110833,Existing
119,123,E32004,Egleston Square at Columbus Ave,Boston,42.315692,-71.098634,Existing
120,124,E32005,Green St T,Boston,42.310579,-71.107341,Existing
121,125,E32006,Jackson Square T at Centre St,Boston,42.322913,-71.100164,Existing
122,126,K32002,Washington Square at Washington St. / Beacon St.,Brookline,42.339335,-71.134930,Existing
123,127,K32004,JFK Crossing at Harvard St. / Thorndike St.,Brookline,42.346563,-71.128374,Existing
124,128,M32004,Kendall T at Main St,Cambridge,42.362457,-71.084970,Existing
125,129,M32015,Harvard University River Houses / Plympton St ...,Cambridge,42.369832,-71.118201,Existing
126,130,M32021,Harvard University Gund Hall at Quincy St / Ki...,Cambridge,42.376369,-71.114025,Existing
127,131,M32022,Lower Cambridgeport at Magazine St/Riverside Rd,Cambridge,42.356954,-71.113687,Existing
128,132,M32023,Harvard University / SEAS Cruft-Pierce Halls a...,Cambridge,42.377945,-71.116865,Existing
129,133,M32024,Harvard University Radcliffe Quadrangle at She...,Cambridge,42.380287,-71.125107,Existing
130,134,M32025,Mass Ave / Linear Park,Cambridge,42.397828,-71.130516,Existing
131,135,M32026,359 Broadway - Broadway at Fayette Street,Cambridge,42.370803,-71.104412,Existing
132,136,M32027,Biogen Idec - Binney St / Sixth St,Cambridge,42.366095,-71.086388,Existing
133,137,M32029,Porter Square Station,Cambridge,42.387995,-71.119084,Existing
134,138,S32005,Wilson Square,Somerville,42.385582,-71.113341,Existing
135,139,S32006,Davis Square,Somerville,42.396969,-71.123024,Existing
136,140,S32007,Ball Square,Somerville,42.400146,-71.112708,Existing
137,141,S32008,Powder House Circle,Somerville,42.400877,-71.116772,Existing
138,142,S32009,Packard Ave / Powderhouse Blvd,Somerville,42.404490,-71.123413,Existing
139,143,S32010,Somerville Hospital at Highland Ave / Crocker St,Somerville,42.390820,-71.109420,Existing
140,144,S32011,Teele Square at 239 Holland St,Somerville,42.402763,-71.126908,Existing
141,145,S32012,Summer St at Cutter St,Somerville,42.394002,-71.120406,Existing

In [10]:
df.describe()

,seq_id,hubway_id,duration,strt_statn,end_statn,birth_date
count,1.579025e+06,1.579025e+06,1.579025e+06,1.579011e+06,1.578980e+06,350644.000000
mean,7.895130e+05,8.865317e+05,1.200280e+03,5.438039e+01,5.425603e+01,1976.295322
std,4.558254e+05,5.064783e+05,2.653539e+04,3.364295e+01,3.347219e+01,10.999742
min,1.000000e+00,8.000000e+00,-6.900000e+03,3.000000e+00,3.000000e+00,1932.000000
25%,3.947570e+05,4.465250e+05,4.120000e+02,2.700000e+01,2.900000e+01,1969.000000
50%,7.895130e+05,8.950440e+05,6.600000e+02,4.800000e+01,4.800000e+01,1979.000000
75%,1.184269e+06,1.328083e+06,1.082000e+03,7.400000e+01,7.400000e+01,1985.000000
max,1.579025e+06,1.748022e+06,1.199446e+07,1.450000e+02,1.450000e+02,1995.000000

* 10 most popular stations
* Distribution of riding duration (histogram)
* Average age of riders
* Pie chart of rider gender
* Most popular zip codes